import type { InteriorLanguageContent } from '../types.ts'

const ca: InteriorLanguageContent = {
  ui: { languageName: 'Idioma', languages: { es: 'Castellà', ca: 'Català', eu: 'Basc', gl: 'Gallec' }, backHome: 'Tornar a l’inici', contents: 'En aquesta pàgina', openContents: 'Mostrar l’índex', foundational: 'PAIDEIA es troba en fase fundacional', explore: 'Continuar explorant', previous: 'Anterior', next: 'Següent', footer: 'Una proposta oberta per aprendre a viure, cuidar el territori i transmetre el que sabem.', photoAlt: 'Héctor en un hort de L’Argentera, sostenint tomàquets acabats de collir', form: { name: 'Nom', email: 'Correu electrònic', profile: 'Perfil', place: 'Localitat o territori', contribution: 'Com t’agradaria contribuir', message: 'Missatge', privacy: 'Accepto que les meves dades s’utilitzin únicament per respondre aquest contacte.', submit: 'Enviar missatge', sending: 'Enviant…', success: 'Gràcies. El missatge s’ha enviat correctament.', error: 'No s’ha pogut enviar. Torna-ho a provar.', profiles: ['Vull ajudar a fundar PAIDEIA', 'Soc un municipi', 'Vull compartir el que sé', 'Vull participar', 'Represento una entitat', 'Puc aportar recursos'] } },
  nav: { proyecto: 'El projecte', territorio: 'Territori', 'como-empezar': 'Com començar', origen: 'Origen', participa: 'Participa' },
  pages: {
    proyecto: { title: 'Una comunitat per aprendre a viure', intro: 'PAIDEIA proposa recuperar la relació entre coneixement, treball, territori i comunitat mitjançant un aprenentatge basat a fer, cuidar, comprendre, compartir i transmetre.', description: 'La filosofia de PAIDEIA: una comunitat d’aprenentatge, treball i vida arrelada en un municipi petit.', sections: [
      { id: 'significado', title: 'Què significa PAIDEIA', paragraphs: ['Paideia (παιδεία) és un terme grec relacionat amb l’educació i la formació de la persona. No es limitava a adquirir informació: comprenia el desenvolupament del criteri, el caràcter, les capacitats i la participació en la vida de la comunitat.', 'PAIDEIA recull aquesta idea com a inspiració, no com un model històric que calgui reproduir. La trasllada al present per preguntar-se com podem aprendre durant tota la vida mitjançant el coneixement, el treball, la cura, la convivència i la transmissió.'] },
      { id: 'que-es', title: 'Què és PAIDEIA', paragraphs: ['Una proposta de comunitat d’aprenentatge, treball i vida arrelada en un municipi petit. No és una escola convencional, un programa assistencial ni una iniciativa turística.', 'És una proposta fundacional que s’haurà de contrastar amb un territori i amb les persones implicades.'] },
      { id: 'por-que', title: 'Per què neix', paragraphs: ['Neix d’una desconnexió més àmplia que el despoblament: ens hem allunyat de processos que sostenen la vida, com produir, reparar, cultivar, cuinar, cuidar, comprendre i transmetre.'] },
      { id: 'principios', title: 'Els cinc principis', paragraphs: ['Els cinc elements del símbol comparteixen un centre: el propòsit d’aprendre a viure.'], bullets: ['Aprendre · obrir-se a comprendre.', 'Fer · convertir coneixement en pràctica.', 'Cuidar · atendre persones, vincles i territori.', 'Compartir · posar capacitats en comú.', 'Transmetre · mantenir viu el coneixement.'] },
      { id: 'aprender-haciendo', title: 'Aprendre fent', paragraphs: ['L’aprenentatge partiria de necessitats i projectes reals: reparar un espai, cuidar un terreny, conservar una collita, documentar un ofici o col·laborar en una necessitat comunitària.', 'S’hauran de definir amb el municipi i els professionals adequats.'] },
      { id: 'ritmos', title: 'Els ritmes de la vida', paragraphs: ['Les estacions, el clima, els cicles naturals i els ritmes de les persones orienten el procés. Respectar-los no elimina el compromís: exigeix responsabilitats realistes i sostingudes.'] },
      { id: 'reciprocidad', title: 'Comunitat i reciprocitat', paragraphs: ['Els participants aprendrien del poble i també hi contribuirien. PAIDEIA no arriba per ensenyar com viure, sinó per aprendre amb els habitants.'] },
      { id: 'maestros', title: 'Mestres i transmissió', paragraphs: ['Un mestre no ha de ser professor ni tenir un títol. El seu saber pot venir d’un ofici, professió, afició, experiència o aprenentatge familiar.'], steps: ['Rebre', 'Practicar', 'Comprendre', 'Aportar', 'Transmetre'] },
      { id: 'tecnologia', title: 'Tecnologia amb propòsit', paragraphs: ['PAIDEIA no rebutja la tecnologia ni idealitza el passat. Prioritza eines comprensibles, reparables, eficients, útils, a escala humana, compatibles amb els límits ecològics i al servei de l’autonomia.'] },
      { id: 'no-es', title: 'Què no és PAIDEIA', bullets: ['No és una escola convencional.', 'No és una comuna aïllada.', 'No és turisme rural.', 'No pretén salvar els pobles.', 'No rebutja els diners ni la tecnologia.', 'No promet el mateix camí per a tothom.'] },
    ] },
    territorio: { title: 'Cuidar les condicions que sostenen la vida', intro: 'PAIDEIA aspira que la seva presència contribueixi a recuperar la capacitat del territori per sostenir vida, coneixement, comunitat i activitat econòmica.', description: 'Territori, regeneració, sostenibilitat i economia al servei de la vida.', sections: [
      { id: 'escenario', title: 'El territori no és un escenari', paragraphs: ['El municipi, els habitants, camps, boscos, tallers, edificis, coneixements i necessitats formen part de l’aprenentatge.'] },
      { id: 'regenerar', title: 'Què significa regenerar', paragraphs: ['Regenerar és contribuir que sòl, aigua, biodiversitat, edificis i relacions comunitàries puguin sostenir vida en el futur.', 'És un compromís i un criteri de decisió, no un impacte promès abans de mesurar-lo.'] },
      { id: 'principios', title: 'Principis ecològics', bullets: ['Recuperar edificis i terrenys abans d’ocupar espais nous.', 'Afavorir materials locals, duradors i reparables.', 'Protegir el sòl i la seva fertilitat.', 'Gestionar l’aigua com un recurs limitat.', 'Afavorir biodiversitat i resiliència.', 'Reparar, reutilitzar i reduir residus.', 'Adaptar la producció a la capacitat del territori.', 'Cuidar els boscos amb criteris ecològics i de prevenció d’incendis.', 'Avaluar l’impacte real.'] },
      { id: 'espacios', title: 'Recuperació d’espais', paragraphs: ['La rehabilitació podria unir aprenentatge, patrimoni, activitat comunitària i opcions futures d’habitatge o treball. Caldran professionals, permisos, supervisió i normativa aplicable.'] },
      { id: 'produccion', title: 'Producció amb límits', paragraphs: ['La producció pot ensenyar i generar valor, però no ha de degradar el territori ni créixer il·limitadament.'] },
      { id: 'economia', title: 'Economia al servei de la vida', paragraphs: ['Volem explorar un model mixt. Una petita producció no finançaria immediatament tota l’estructura.'], bullets: ['Administracions i convocatòries.', 'Fundacions, entitats i empreses.', 'Donacions i cessions.', 'Aportacions quan sigui possible.', 'Ingressos de productes, serveis o activitats.', 'Projectes autònoms o cooperatius.'] },
      { id: 'criterio', title: 'Un criteri per decidir', quote: 'Una activitat no serà valuosa només perquè ensenyi o generi ingressos. També haurà de respectar els límits del territori i, sempre que sigui possible, contribuir a regenerar-lo.' },
    ] },
    'como-empezar': { title: 'Començar petit. Aprendre de la realitat.', intro: 'PAIDEIA no necessita començar com una gran institució. Necessita reunir un nucli humà capaç, escoltar un territori i construir un primer pilot que es pugui provar amb honestedat.', description: 'Full de ruta fundacional, escala inicial i recursos per a un primer pilot.', status: 'FASE ACTUAL: CONSTRUCCIÓ DEL NUCLI FUNDADOR', sections: [
      { id: 'fase-1', eyebrow: 'Fase 1 · Actual', title: 'Reunir el nucli fundador', paragraphs: ['Objectiu: passar d’una iniciativa impulsada per una persona a un equip petit que comparteixi responsabilitat.'], bullets: ['Entre 3 i 6 persones com a referència inicial, no com a requisit tancat.', 'Definir principis, límits i govern.', 'Distribuir responsabilitats i contrastar el model.', 'Estudiar la forma jurídica i l’economia del pilot.', 'Crear una primera xarxa de col·laboració.'] },
      { id: 'fase-2', eyebrow: 'Fase 2', title: 'Escoltar i triar un territori', bullets: ['Parlar amb municipis, entitats i veïnat.', 'Identificar sabers, oficis i possibles mestres.', 'Detectar espais, terrenys i necessitats.', 'Avaluar habitatge, aigua, mobilitat, connectivitat i serveis.'] },
      { id: 'fase-3', eyebrow: 'Fase 3', title: 'Dissenyar el pilot', bullets: ['Definir participants i entre 2 i 4 projectes reals.', 'Reunir mestres i professionals.', 'Resoldre convivència i acompanyament.', 'Preparar pressupost, finançament, assegurances, permisos i prevenció.', 'Definir indicadors i protecció de menors si cal.'] },
      { id: 'fase-4', eyebrow: 'Fase 4', title: 'Fer, avaluar i corregir', bullets: ['Executar els projectes.', 'Avaluar aprenentatge, autonomia i convivència.', 'Mesurar utilitat comunitària i impacte territorial.', 'Calcular el cost real.', 'Decidir què mantenir, modificar o abandonar.'] },
      { id: 'fase-5', eyebrow: 'Fase 5', title: 'Consolidar o compartir', paragraphs: ['Només després del pilot es valoraria consolidar el projecte o ajudar altres comunitats. No seria una expansió centralitzada ni una franquícia.'] },
      { id: 'piloto', title: 'Primer pilot · aproximació inicial', bullets: ['Un municipi petit.', 'Entre 8 i 12 participants.', 'Diversos mesos.', 'Una casa o espai base.', 'Mestres locals i professionals externs.', 'Entre 2 i 4 projectes reals.', 'Avaluació personal, comunitària, econòmica i territorial.'], paragraphs: ['Són una escala de treball inicial, no compromisos tancats.'] },
      { id: 'capacidades', title: 'Capacitats necessàries', bullets: ['Visió i coordinació.', 'Operacions i administració.', 'Acompanyament educatiu.', 'Facilitació i convivència.', 'Territori i regeneració.', 'Oficis i seguretat.', 'Economia i producció.', 'Comunicació i aliances.', 'Comunitat i coneixement local.'], quote: 'No busquem títols ni completar un organigrama. Busquem persones fiables, capaces d’escoltar, col·laborar i assumir responsabilitats reals.' },
      { id: 'recursos', title: 'Què necessita el pilot', bullets: ['Persones i municipi.', 'Espai base i habitatge.', 'Terrenys, tallers i eines.', 'Alimentació i mobilitat.', 'Finançament.', 'Assegurances i assessorament legal.', 'Xarxa de mestres i projectes reals.', 'Temps de preparació.'] },
      { id: 'medicion', title: 'Com es mesuraria', bullets: ['Autonomia i capacitats.', 'Coneixements transmesos i continuïtat.', 'Necessitats comunitàries ateses.', 'Espais recuperats i estat ecològic.', 'Activitats econòmiques iniciades.', 'Qualitat de la convivència.', 'Cost i sostenibilitat.'] },
      { id: 'limites', title: 'Expectatives i límits', quote: 'PAIDEIA no promet resoldre tota sola el despoblament, l’atur juvenil ni la pèrdua d’oficis. L’expectativa inicial és reunir un nucli capaç, trobar un territori disposat a col·laborar i comprovar amb un pilot petit si aquesta manera d’aprendre, contribuir i conviure genera valor real.' },
    ] },
    origen: { title: 'D’on neix PAIDEIA', intro: 'PAIDEIA neix d’una manera d’entendre l’aprenentatge: fer servir les mans i el cap, cuidar allò proper i compartir el que descobrim.', description: 'L’origen de PAIDEIA i el paper inicial d’Héctor.', sections: [
      { id: 'origen', title: 'Aprendre amb les mans i el cap', paragraphs: ['Soc l’Héctor i visc a L’Argentera, un poble petit de Tarragona. Des de petit, a casa em van ensenyar a fer servir les mans i el cap i a no separar una cosa de l’altra.', 'Vaig aprendre a moure’m entre àmbits molt diferents: construcció, electricitat, fontaneria, cuina, jardineria, història, art, filosofia o ciència. Sovint també va ser una qüestió de necessitat: no sempre teníem gaires diners, però sí temps, curiositat i enginy per entendre com estaven fetes les coses i aprendre a resoldre-les.', 'Això no vol dir que sigui expert en totes aquestes matèries. Vol dir que he crescut entenent el coneixement com una cosa viva: s’observa, es pregunta, es practica, es corregeix i es comparteix. Mai no deixem d’aprendre.'] },
      { id: 'vida-cotidiana', title: 'Una pràctica quotidiana', paragraphs: ['Avui treballo com a informàtic, però mantinc el meu propi hort, faig reformes a casa i preparo els meus propis embotits i conserves. En cada tasca busco aprendre, fer les coses amb cura i oferir als meus la millor qualitat i el més natural que estigui al meu abast.', 'També m’agrada compartir, explicar històries i curiositats, i pensar que algun dia transmetré tot això al meu fill. No com un conjunt de respostes tancades, sinó com una manera de mirar el món amb atenció, autonomia i ganes de continuar descobrint.'] },
      { id: 'pregunta', title: 'Del que és personal a una pregunta comuna', paragraphs: ['PAIDEIA neix d’aquesta experiència i del desig de fomentar el saber, la calma, l’enginy, la cura i l’altruisme. I d’una pregunta: què passaria si tornéssim a crear llocs on aprendre fent, sentir-nos útils, cuidar un territori i transmetre allò que sabem?', 'He formulat i fet pública aquesta primera proposta, però no vull construir-la sol ni presentar-la com una idea acabada. Tampoc pretenc ocupar un lloc d’expert en àmbits que necessiten coneixements i experiències diferents dels meus.'] },
      { id: 'publico', title: 'Per què fer-ho públic', paragraphs: ['Una idea de comunitat no es pot desenvolupar de manera privada o individual. Fer-la pública incorpora preguntes, desacords, coneixements i aliances.'] },
      { id: 'papel', title: 'El meu paper inicial', paragraphs: ['El meu paper inicial és impulsar la conversa, connectar persones diferents, organitzar els primers passos i ajudar a convertir una intuïció en una proposta que es pugui contrastar amb la realitat.', 'No busco seguidors d’una idea acabada. Busco persones amb qui qüestionar-la, millorar-la i compartir progressivament la responsabilitat. PAIDEIA no hauria de dependre d’una sola persona.'] },
      { id: 'busco', title: 'Què busco ara', bullets: ['Persones fundadores.', 'Experiència educativa i comunitària.', 'Coneixement ambiental i rural.', 'Mestres i professionals.', 'Municipis interessats.', 'Assessorament jurídic i econòmic.', 'Entitats i possibles col·laboradors.'] },
      { id: 'no-quiero', title: 'Què no vull que sigui', bullets: ['Un projecte personalista.', 'Una promesa grandiloqüent.', 'Una iniciativa imposada des de fora.', 'Una idealització de la vida rural.', 'Una marca sense activitat real.', 'Una organització que creixi perdent el propòsit.'] },
    ] },
    participa: { title: 'PAIDEIA comença reunint capacitats diferents', intro: 'No busquem només suport a una idea. Busquem persones, municipis i entitats disposats a explorar què podrien construir amb altres.', description: 'Formes de participar en la fase fundacional i contacte.', sections: [
      { id: 'fundar', title: 'Vull ajudar a fundar PAIDEIA', paragraphs: ['Per a persones que vulguin compartir responsabilitat, decisions i treball sostingut.'] }, { id: 'municipio', title: 'Soc un municipi', paragraphs: ['Per a ajuntaments o agents locals que vulguin explorar un possible pilot sense compromisos previs.'] }, { id: 'compartir', title: 'Vull compartir el que sé', paragraphs: ['Per a sabers d’un ofici, professió, afició, experiència o transmissió familiar. No cal ser docent.'] }, { id: 'participar', title: 'Vull participar', paragraphs: ['Per a persones interessades en una experiència futura. Encara no hi ha convocatòria ni calendari tancats.'] }, { id: 'entidad', title: 'Represento una entitat', paragraphs: ['Per a associacions, fundacions, empreses, administracions o centres educatius.'] }, { id: 'recursos', title: 'Puc aportar recursos', paragraphs: ['Espais, terrenys, eines, materials, finançament, temps o connexions poden respondre a necessitats reals.'] }, { id: 'contacto', title: 'Obrim la conversa', paragraphs: ['Explica’ns des d’on escrius i què voldries explorar. Contactar no implica cap compromís.'] },
    ] },
  },
}
export default ca
