import type { InteriorLanguageContent } from '../types.ts'

const eu: InteriorLanguageContent = {
  ui: { languageName: 'Hizkuntza', languages: { es: 'Gaztelania', ca: 'Katalana', eu: 'Euskara', gl: 'Galiziera' }, backHome: 'Hasierara itzuli', contents: 'Orrialde honetan', openContents: 'Aurkibidea erakutsi', foundational: 'PAIDEIA sorrera-fasean dago', explore: 'Jarraitu aztertzen', previous: 'Aurrekoa', next: 'Hurrengoa', footer: 'Bizitzen ikasteko, lurraldea zaintzeko eta dakiguna transmititzeko proposamen irekia.', photoAlt: 'Héctor L’Argenterako baratze batean, bildu berri diren tomateak eskuetan', form: { name: 'Izena', email: 'Posta elektronikoa', profile: 'Profila', place: 'Herria edo lurraldea', contribution: 'Nola lagundu nahiko zenuke', message: 'Mezua', privacy: 'Onartzen dut nire datuak harreman honi erantzuteko soilik erabiltzea.', submit: 'Mezua bidali', sending: 'Bidaltzen…', success: 'Eskerrik asko. Mezua behar bezala bidali da.', error: 'Ezin izan da bidali. Saiatu berriro.', profiles: ['PAIDEIA sortzen lagundu nahi dut', 'Udal bat naiz', 'Dakidana partekatu nahi dut', 'Parte hartu nahi dut', 'Erakunde bat ordezkatzen dut', 'Baliabideak eskain ditzaket'] } },
  nav: { proyecto: 'Proiektua', territorio: 'Lurraldea', 'como-empezar': 'Nola hasi', origen: 'Jatorria', participa: 'Parte hartu' },
  pages: {
    proyecto: { title: 'Bizitzen ikasteko komunitatea', intro: 'PAIDEIAk ezagutzaren, lanaren, lurraldearen eta komunitatearen arteko harremana berreskuratzea proposatzen du, eginez, zainduz, ulertuz, partekatuz eta transmitituz ikasteko.', description: 'PAIDEIAren filosofia: herri txiki batean errotutako ikaskuntza-, lan- eta bizitza-komunitatea.', sections: [
      { id: 'significado', title: 'Zer esan nahi du PAIDEIAk', paragraphs: ['Paideia (παιδεία) hezkuntzarekin eta pertsonaren prestakuntzarekin lotutako grezierazko terminoa da. Ez zen informazioa eskuratzera mugatzen: irizpidea, izaera, gaitasunak eta komunitateko bizitzan parte hartzea garatzea ere barne hartzen zuen.', 'PAIDEIAk ideia hori inspirazio gisa hartzen du, ez erreproduzitu beharreko eredu historiko gisa. Gaur egunera ekartzen du, ezagutzaren, lanaren, zaintzaren, bizikidetzaren eta transmisioaren bidez bizitza osoan nola ikasi dezakegun galdetzeko.'] },
      { id: 'que-es', title: 'Zer da PAIDEIA', paragraphs: ['Herri txiki batean errotutako ikaskuntza-, lan- eta bizitza-komunitate baten proposamena da. Ez da ohiko eskola, laguntza-programa edo turismo-ekimena.', 'Sorrera-faseko proposamena da, eta lurraldearekin eta parte hartuko duten pertsonekin egiaztatu beharko da.'] },
      { id: 'por-que', title: 'Zergatik sortu da', paragraphs: ['Despopulazioa baino deskonexio zabalago batetik sortu da: bizitza sostengatzen duten prozesuetatik urrundu gara, hala nola ekoiztea, konpontzea, lantzea, prestatzea, zaintzea, ulertzea eta transmititzea.'] },
      { id: 'principios', title: 'Bost printzipioak', paragraphs: ['Sinboloaren bost elementuek erdigune bera dute: bizitzen ikasteko helburua.'], bullets: ['Ikasi · ulertzeko prest egon.', 'Egin · ezagutza praktikara eraman.', 'Zaindu · pertsonak, loturak eta lurraldea artatu.', 'Partekatu · gaitasunak erkidean jarri.', 'Transmititu · ezagutza bizirik mantendu.'] },
      { id: 'aprender-haciendo', title: 'Eginez ikasi', paragraphs: ['Ikaskuntza benetako behar eta proiektuetatik abiatuko litzateke: espazio bat konpontzea, lur bat zaintzea, uzta kontserbatzea, lanbide bat dokumentatzea edo komunitate-behar batean laguntzea.', 'Udalarekin eta profesional egokiekin definitu beharko dira.'] },
      { id: 'ritmos', title: 'Bizitzaren erritmoak', paragraphs: ['Urtaroek, klimak, ziklo naturalek eta pertsonen erritmoek prozesua gidatzen dute. Horiek errespetatzeak ez du konpromisoa kentzen: erantzukizun errealistak eta iraunkorrak eskatzen ditu.'] },
      { id: 'reciprocidad', title: 'Komunitatea eta elkarrekikotasuna', paragraphs: ['Parte-hartzaileek herritik ikasiko lukete eta hari ekarpena ere egingo liokete. PAIDEIA ez da herri bati nola bizi irakastera iristen, bertako biztanleekin ikastera baizik.'] },
      { id: 'maestros', title: 'Maisuak eta transmisioa', paragraphs: ['Maisu batek ez du zertan irakasle edo tituludun izan. Jakintza lanbide, zaletasun, esperientzia edo familia-ikaskuntza batetik etor daiteke.'], steps: ['Jaso', 'Praktikatu', 'Ulertu', 'Ekarri', 'Transmititu'] },
      { id: 'tecnologia', title: 'Helburua duen teknologia', paragraphs: ['PAIDEIAk ez du teknologia baztertzen eta ez du iragana idealizatzen. Tresna ulergarri, konpongarri, eraginkor eta erabilgarriak lehenesten ditu, giza eskalara egokituak, muga ekologikoekin bateragarriak eta autonomiaren zerbitzura.'] },
      { id: 'no-es', title: 'Zer ez da PAIDEIA', bullets: ['Ez da ohiko eskola.', 'Ez da komuna isolatua.', 'Ez da landa-turismoa.', 'Ez du herriak salbatu nahi.', 'Ez du dirua edo teknologia baztertzen.', 'Ez du bide bera agintzen pertsona guztientzat.'] },
    ] },
    territorio: { title: 'Bizitza sostengatzen duten baldintzak zaindu', intro: 'PAIDEIAk lurraldeak bizitza, ezagutza, komunitatea eta jarduera ekonomikoa sostengatzeko duen gaitasuna berreskuratzen lagundu nahi du.', description: 'Lurraldea, birsorkuntza, jasangarritasuna eta bizitzaren zerbitzura dagoen ekonomia.', sections: [
      { id: 'escenario', title: 'Lurraldea ez da agertoki bat', paragraphs: ['Udalerria, bertako biztanleak, soroak, basoak, tailerrak, eraikinak, ezagutzak eta beharrak ikaskuntzaren parte dira.'] },
      { id: 'regenerar', title: 'Zer da birsortzea', paragraphs: ['Birsortzea lurzorua, ura, biodibertsitatea, eraikinak eta komunitate-harremanak etorkizunean bizitza sostengatzeko hobeto prestatzen laguntzea da.', 'Konpromisoa eta erabaki-irizpidea da, ez neurtu aurretik agindutako eragina.'] },
      { id: 'principios', title: 'Printzipio ekologikoak', bullets: ['Eraikinak eta lurrak berreskuratu espazio berriak hartu aurretik.', 'Tokiko material iraunkor eta konpongarriak erabili.', 'Lurzorua eta emankortasuna babestu.', 'Ura baliabide mugatu gisa kudeatu.', 'Biodibertsitatea eta erresilientzia sustatu.', 'Konpondu, berrerabili eta hondakinak murriztu.', 'Ekoizpena lurraldearen gaitasunera egokitu.', 'Basoak irizpide ekologikoekin eta suteak prebenituz zaindu.', 'Benetako eragina ebaluatu.'] },
      { id: 'espacios', title: 'Espazioak berreskuratzea', paragraphs: ['Birgaitzeak ikaskuntza, ondarea, komunitate-jarduera eta etorkizuneko etxebizitza edo lana lotu litzake. Profesionalak, baimenak, gainbegiratzea eta araudia beharko dira.'] },
      { id: 'produccion', title: 'Mugak dituen ekoizpena', paragraphs: ['Ekoizpenak ikasteko eta balioa sortzeko balio dezake, baina ez du lurraldea hondatu edo mugarik gabe hazi behar.'] },
      { id: 'economia', title: 'Bizitzaren zerbitzura dagoen ekonomia', paragraphs: ['Eredu mistoa aztertu nahi dugu. Ekoizpen txiki batek ez luke berehala egitura osoa finantzatuko.'], bullets: ['Administrazioak eta deialdiak.', 'Fundazioak, erakundeak eta enpresak.', 'Dohaintzak eta lagapenak.', 'Ahal denean, parte-hartzaileen ekarpenak.', 'Produktu, zerbitzu edo jardueren diru-sarrerak.', 'Proiektu autonomo edo kooperatiboak.'] },
      { id: 'criterio', title: 'Erabakitzeko irizpidea', quote: 'Jarduera bat ez da baliotsua izango irakasten duelako edo diru-sarrerak sortzen dituelako bakarrik. Lurraldearen mugak ere errespetatu beharko ditu eta, ahal denean, haren birsorkuntzan lagundu.' },
    ] },
    'como-empezar': { title: 'Txiki hasi. Errealitatetik ikasi.', intro: 'PAIDEIAk ez du erakunde handi gisa hasi behar. Giza nukleo gai bat bildu, lurralde bat entzun eta zintzotasunez probatu daitekeen lehen pilotua eraiki behar du.', description: 'Sorrera-ibilbidea, hasierako eskala eta lehen piloturako baliabideak.', status: 'UNEA: TALDE SORTZAILEA ERAIKITZEA', sections: [
      { id: 'fase-1', eyebrow: '1. fasea · Unekoa', title: 'Talde sortzailea bildu', paragraphs: ['Helburua: pertsona batek bultzatutako ekimenetik erantzukizuna partekatzen duen talde txiki batera igarotzea.'], bullets: ['3 eta 6 pertsona artean hasierako erreferentzia gisa, ez baldintza itxi gisa.', 'Printzipioak, mugak eta gobernantza definitu.', 'Erantzukizunak banatu eta eredua profesionalekin egiaztatu.', 'Forma juridikoa eta pilotuaren ekonomia aztertu.', 'Lehen lankidetza-sarea sortu.'] },
      { id: 'fase-2', eyebrow: '2. fasea', title: 'Lurralde bat entzun eta aukeratu', bullets: ['Udalekin, erakundeekin eta auzotarrekin hitz egin.', 'Jakintzak, lanbideak eta maisu posibleak identifikatu.', 'Espazioak, lurrak eta beharrak antzeman.', 'Etxebizitza, ura, mugikortasuna, konektibitatea eta zerbitzuak ebaluatu.'] },
      { id: 'fase-3', eyebrow: '3. fasea', title: 'Pilotua diseinatu', bullets: ['Parte-hartzaileak eta 2-4 benetako proiektu definitu.', 'Maisuak eta profesionalak bildu.', 'Bizikidetza eta laguntza antolatu.', 'Aurrekontua, finantzaketa, aseguruak, baimenak eta prebentzioa prestatu.', 'Adierazleak eta adingabeen babesa definitu, beharrezkoa bada.'] },
      { id: 'fase-4', eyebrow: '4. fasea', title: 'Egin, ebaluatu eta zuzendu', bullets: ['Proiektuak gauzatu.', 'Ikaskuntza, autonomia eta bizikidetza ebaluatu.', 'Komunitate-erabilgarritasuna eta lurralde-eragina neurtu.', 'Benetako kostua kalkulatu.', 'Zer mantendu, aldatu edo utzi erabaki.'] },
      { id: 'fase-5', eyebrow: '5. fasea', title: 'Sendotu edo partekatu', paragraphs: ['Pilotuaren ondoren bakarrik baloratuko da proiektua sendotzea edo beste komunitate batzuk sortzen laguntzea. Ez litzateke hedapen zentralizatua edo frankizia izango.'] },
      { id: 'piloto', title: 'Lehen pilotua · hasierako hurbilketa', bullets: ['Herri txiki bat.', '8 eta 12 parte-hartzaile artean.', 'Hainbat hilabete.', 'Etxe edo oinarrizko espazio bat.', 'Tokiko maisuak eta kanpoko profesionalak.', '2 eta 4 benetako proiektu artean.', 'Ebaluazio pertsonala, komunitarioa, ekonomikoa eta lurraldekoa.'], paragraphs: ['Lan-eskala hasierakoa da, ez konpromiso itxia.'] },
      { id: 'capacidades', title: 'Behar diren gaitasunak', bullets: ['Ikuspegia eta koordinazioa.', 'Eragiketak eta administrazioa.', 'Hezkuntza-laguntza.', 'Bideratzea eta bizikidetza.', 'Lurraldea eta birsorkuntza.', 'Lanbideak eta segurtasuna.', 'Ekonomia eta ekoizpena.', 'Komunikazioa eta aliantzak.', 'Komunitatea eta tokiko ezagutza.'], quote: 'Ez ditugu tituluak bildu edo organigrama bat bete nahi. Pertsona fidagarriak behar ditugu, entzuteko, lankidetzan aritzeko eta benetako erantzukizunak hartzeko gai direnak.' },
      { id: 'recursos', title: 'Zer behar du pilotuak', bullets: ['Pertsonak eta udalerria.', 'Oinarrizko espazioa eta etxebizitza.', 'Lurrak, tailerrak eta tresnak.', 'Elikadura eta mugikortasuna.', 'Finantzaketa.', 'Aseguruak eta lege-aholkularitza.', 'Maisuen sarea eta benetako proiektuak.', 'Prestatzeko denbora.'] },
      { id: 'medicion', title: 'Nola neurtuko litzateke', bullets: ['Autonomia eta gaitasunak.', 'Transmititutako ezagutzak eta jarraitutasuna.', 'Artatutako komunitate-beharrak.', 'Berreskuratutako espazioak eta egoera ekologikoa.', 'Abiatutako jarduera ekonomikoak.', 'Bizikidetzaren kalitatea.', 'Kostua eta jasangarritasuna.'] },
      { id: 'limites', title: 'Itxaropenak eta mugak', quote: 'PAIDEIAk ez du bere kabuz despopulazioa, gazteen langabezia edo lanbideen galera konpontzea agintzen. Hasierako itxaropena zehatzagoa da: talde gai bat biltzea, lankidetzarako lurralde bat aurkitzea eta pilotu txiki batekin ikasteko, laguntzeko eta elkarrekin bizitzeko modu honek benetako balioa sortzen duen egiaztatzea.' },
    ] },
    origen: { title: 'Nondik dator PAIDEIA', intro: 'PAIDEIA ikaskuntza ulertzeko modu batetik sortu da: eskuak eta burua erabiltzea, gertukoa zaintzea eta aurkitzen duguna partekatzea.', description: 'PAIDEIAren jatorria eta Héctorren hasierako eginkizuna.', sections: [
      { id: 'origen', title: 'Eskuekin eta buruarekin ikasi', paragraphs: ['Héctor naiz eta L’Argenteran bizi naiz, Tarragonako herri txiki batean. Txikitatik, etxean eskuak eta burua erabiltzen eta bata bestetik ez bereizten irakatsi zidaten.', 'Oso arlo desberdinetan moldatzen ikasi nuen: igeltserotza, elektrizitatea, iturgintza, sukaldaritza, lorezaintza, historia, artea, filosofia edo zientzia. Askotan beharragatik ere izan zen: ez genuen beti diru askorik, baina bai denbora, jakin-mina eta asmamena gauzak nola eginda zeuden ulertzeko eta konpontzen ikasteko.', 'Horrek ez du esan nahi gai horietan guztietan aditua naizenik. Ezagutza bizia dela ulertuz hazi naizela esan nahi du: behatu, galdetu, praktikatu, zuzendu eta partekatu egiten da. Ez diogu inoiz ikasteari uzten.'] },
      { id: 'vida-cotidiana', title: 'Eguneroko praktika', paragraphs: ['Gaur egun informatikari gisa lan egiten dut, baina nire baratzea mantentzen dut, etxeko berrikuntzak egiten ditut eta nire hestebeteak eta kontserbak prestatzen ditut. Zeregin bakoitzean ikasi, gauzak arretaz egin eta nire ingurukoei nire esku dagoen kalitaterik onena eta naturalena eskaini nahi diet.', 'Partekatzea, istorioak eta bitxikeriak kontatzea ere gustatzen zait, eta noizbait hori guztia nire semeari transmitituko diodala pentsatzea. Ez erantzun itxien bilduma gisa, mundua arretaz, autonomiaz eta aurkitzen jarraitzeko gogoz begiratzeko modu gisa baizik.'] },
      { id: 'pregunta', title: 'Esperientzia pertsonaletik galdera komunera', paragraphs: ['PAIDEIA esperientzia horretatik eta jakintza, lasaitasuna, asmamena, zaintza eta altruismoa sustatzeko nahitik sortu da. Eta galdera batetik: zer gertatuko litzateke eginez ikasteko, baliagarri sentitzeko, lurraldea zaintzeko eta dakiguna transmititzeko lekuak berriro sortuko bagenitu?', 'Lehen proposamen honi forma eman eta publiko egin diot, baina ez dut bakarrik eraiki edo amaitutako ideia gisa aurkeztu nahi. Ez dut nire ezagutzetatik bestelako esperientziak behar dituzten arloetan adituaren lekua hartu nahi.'] },
      { id: 'publico', title: 'Zergatik egin publiko', paragraphs: ['Komunitate-ideia bat ezin da modu pribatu edo indibidualean garatu. Publiko egiteak galderak, desadostasunak, ezagutzak eta aliantzak gehitzen ditu.'] },
      { id: 'papel', title: 'Nire hasierako zeregina', paragraphs: ['Nire hasierako zeregina elkarrizketa bultzatzea, pertsona desberdinak lotzea, lehen urratsak antolatzea eta intuizio bat errealitatearekin egiaztatu daitekeen proposamen bihurtzen laguntzea da.', 'Ez dut amaitutako ideia baten jarraitzailerik bilatzen. Zalantzan jarri, hobetu eta erantzukizuna pixkanaka partekatuko duten pertsonak bilatzen ditut. PAIDEIAk ez luke pertsona bakar baten mende egon behar.'] },
      { id: 'busco', title: 'Zer bilatzen dut orain', bullets: ['Pertsona sortzaileak.', 'Hezkuntza- eta komunitate-esperientzia.', 'Ingurumen- eta landa-ezagutza.', 'Maisuak eta profesionalak.', 'Interesa duten udalerriak.', 'Lege- eta ekonomia-aholkularitza.', 'Erakundeak eta laguntzaile posibleak.'] },
      { id: 'no-quiero', title: 'Zer ez dut nahi izatea', bullets: ['Proiektu pertsonalista.', 'Promesa handinahikoa.', 'Kanpotik inposatutako ekimena.', 'Landa-bizitzaren idealizazioa.', 'Benetako jarduerarik gabeko marka.', 'Helburua galduz hazten den erakundea.'] },
    ] },
    participa: { title: 'PAIDEIA gaitasun desberdinak bilduz hasten da', intro: 'Ez dugu ideia bati babesa bakarrik bilatzen. Besteekin zer eraiki lezaketen aztertzeko prest dauden pertsonak, udalerriak eta erakundeak bilatzen ditugu.', description: 'PAIDEIAren sorrera-fasean parte hartzeko moduak eta harremana.', sections: [
      { id: 'fundar', title: 'PAIDEIA sortzen lagundu nahi dut', paragraphs: ['Hasierako etapan erantzukizuna, erabakiak eta lan iraunkorra partekatu nahi dutenentzat.'] }, { id: 'municipio', title: 'Udal bat naiz', paragraphs: ['Konpromisorik gabe pilotu posible bat aztertu nahi duten udal edo tokiko eragileentzat.'] }, { id: 'compartir', title: 'Dakidana partekatu nahi dut', paragraphs: ['Lanbide, zaletasun, esperientzia edo familia-transmisiotik datorren ezagutzarentzat. Ez da beharrezkoa irakaslea izatea.'] }, { id: 'participar', title: 'Parte hartu nahi dut', paragraphs: ['Etorkizuneko esperientzia batean interesa dutenentzat. Oraindik ez dago deialdi edo egutegi itxirik.'] }, { id: 'entidad', title: 'Erakunde bat ordezkatzen dut', paragraphs: ['Elkarte, fundazio, enpresa, administrazio edo ikastetxeentzat.'] }, { id: 'recursos', title: 'Baliabideak eskain ditzaket', paragraphs: ['Espazioak, lurrak, tresnak, materialak, finantzaketa, denbora edo harremanak benetako beharrei erantzuteko erabilgarriak izan daitezke.'] }, { id: 'contacto', title: 'Elkarrizketa ireki dezagun', paragraphs: ['Esaguzu nondik idazten duzun eta zer aztertu nahiko zenukeen. Harremanetan jartzeak ez dakar konpromisorik.'] },
    ] },
  },
}
export default eu
