import type { InteriorLanguageContent } from '../types.ts'

const gl: InteriorLanguageContent = {
  ui: { languageName: 'Idioma', languages: { es: 'Castelán', ca: 'Catalán', eu: 'Éuscaro', gl: 'Galego' }, backHome: 'Volver ao inicio', contents: 'Nesta páxina', openContents: 'Mostrar o índice', foundational: 'PAIDEIA atópase en fase fundacional', explore: 'Seguir explorando', previous: 'Anterior', next: 'Seguinte', footer: 'Unha proposta aberta para aprender a vivir, coidar o territorio e transmitir o que sabemos.', photoAlt: 'Héctor nunha horta de L’Argentera, sostendo tomates acabados de recoller', form: { name: 'Nome', email: 'Correo electrónico', profile: 'Perfil', place: 'Localidade ou territorio', contribution: 'Como che gustaría contribuír', message: 'Mensaxe', privacy: 'Acepto que os meus datos se utilicen unicamente para responder a este contacto.', submit: 'Enviar mensaxe', sending: 'Enviando…', success: 'Grazas. A mensaxe enviouse correctamente.', error: 'Non se puido enviar. Téntao de novo.', profiles: ['Quero axudar a fundar PAIDEIA', 'Son un municipio', 'Quero compartir o que sei', 'Quero participar', 'Represento unha entidade', 'Podo achegar recursos'] } },
  nav: { proyecto: 'O proxecto', territorio: 'Territorio', 'como-empezar': 'Como comezar', origen: 'Orixe', participa: 'Participa' },
  pages: {
    proyecto: { title: 'Unha comunidade para aprender a vivir', intro: 'PAIDEIA propón recuperar a relación entre coñecemento, traballo, territorio e comunidade mediante unha aprendizaxe baseada en facer, coidar, comprender, compartir e transmitir.', description: 'A filosofía de PAIDEIA: unha comunidade de aprendizaxe, traballo e vida arraigada nun municipio pequeno.', sections: [
      { id: 'significado', title: 'Que significa PAIDEIA', paragraphs: ['Paideia (παιδεία) é un termo grego relacionado coa educación e coa formación da persoa. Non se limitaba a adquirir información: comprendía o desenvolvemento do criterio, o carácter, as capacidades e a participación na vida da comunidade.', 'PAIDEIA recolle esta idea como inspiración, non como un modelo histórico que haxa que reproducir. Tráea ao presente para preguntarse como podemos aprender durante toda a vida mediante o coñecemento, o traballo, o coidado, a convivencia e a transmisión.'] },
      { id: 'que-es', title: 'Que é PAIDEIA', paragraphs: ['Unha proposta de comunidade de aprendizaxe, traballo e vida arraigada nun municipio pequeno. Non é unha escola convencional, un programa asistencial nin unha iniciativa turística.', 'É unha proposta fundacional que deberá contrastarse cun territorio e coas persoas implicadas.'] },
      { id: 'por-que', title: 'Por que nace', paragraphs: ['Nace dunha desconexión máis ampla ca o despoboamento: afastámonos de procesos que sosteñen a vida, como producir, reparar, cultivar, cociñar, coidar, comprender e transmitir.'] },
      { id: 'principios', title: 'Os cinco principios', paragraphs: ['Os cinco elementos do símbolo comparten un centro: o propósito de aprender a vivir.'], bullets: ['Aprender · abrirse a comprender.', 'Facer · converter coñecemento en práctica.', 'Coidar · atender persoas, vínculos e territorio.', 'Compartir · poñer capacidades en común.', 'Transmitir · manter vivo o coñecemento.'] },
      { id: 'aprender-haciendo', title: 'Aprender facendo', paragraphs: ['A aprendizaxe partiría de necesidades e proxectos reais: reparar un espazo, coidar un terreo, conservar unha colleita, documentar un oficio ou colaborar nunha necesidade comunitaria.', 'Deberán definirse co municipio e cos profesionais axeitados.'] },
      { id: 'ritmos', title: 'Os ritmos da vida', paragraphs: ['As estacións, o clima, os ciclos naturais e os ritmos das persoas orientan o proceso. Respectalos non elimina o compromiso: esixe responsabilidades realistas e sostidas.'] },
      { id: 'reciprocidad', title: 'Comunidade e reciprocidade', paragraphs: ['As persoas participantes aprenderían da vila e tamén contribuirían a ela. PAIDEIA non chega para ensinar como vivir, senón para aprender cos seus habitantes.'] },
      { id: 'maestros', title: 'Mestres e transmisión', paragraphs: ['Un mestre non ten que ser profesor nin ter un título. O saber pode proceder dun oficio, profesión, afección, experiencia ou aprendizaxe familiar.'], steps: ['Recibir', 'Practicar', 'Comprender', 'Achegar', 'Transmitir'] },
      { id: 'tecnologia', title: 'Tecnoloxía con propósito', paragraphs: ['PAIDEIA non rexeita a tecnoloxía nin idealiza o pasado. Prioriza ferramentas comprensibles, reparables, eficientes, útiles, a escala humana, compatibles cos límites ecolóxicos e ao servizo da autonomía.'] },
      { id: 'no-es', title: 'Que non é PAIDEIA', bullets: ['Non é unha escola convencional.', 'Non é unha comuna illada.', 'Non é turismo rural.', 'Non pretende salvar as vilas.', 'Non rexeita o diñeiro nin a tecnoloxía.', 'Non promete o mesmo camiño para todas as persoas.'] },
    ] },
    territorio: { title: 'Coidar as condicións que sosteñen a vida', intro: 'PAIDEIA aspira a que a súa presenza contribúa a recuperar a capacidade do territorio para soster vida, coñecemento, comunidade e actividade económica.', description: 'Territorio, rexeneración, sustentabilidade e economía ao servizo da vida.', sections: [
      { id: 'escenario', title: 'O territorio non é un escenario', paragraphs: ['O municipio, os habitantes, campos, bosques, talleres, edificios, coñecementos e necesidades forman parte da aprendizaxe.'] },
      { id: 'regenerar', title: 'Que significa rexenerar', paragraphs: ['Rexenerar é contribuír a que solo, auga, biodiversidade, edificios e relacións comunitarias poidan soster vida no futuro.', 'É un compromiso e un criterio de decisión, non un impacto prometido antes de medilo.'] },
      { id: 'principios', title: 'Principios ecolóxicos', bullets: ['Recuperar edificios e terreos antes de ocupar espazos novos.', 'Favorecer materiais locais, duradeiros e reparables.', 'Protexer o solo e a súa fertilidade.', 'Xestionar a auga como recurso limitado.', 'Favorecer biodiversidade e resiliencia.', 'Reparar, reutilizar e reducir residuos.', 'Adaptar a produción á capacidade do territorio.', 'Coidar os bosques con criterios ecolóxicos e de prevención de incendios.', 'Avaliar o impacto real.'] },
      { id: 'espacios', title: 'Recuperación de espazos', paragraphs: ['A rehabilitación podería unir aprendizaxe, patrimonio, actividade comunitaria e opcións futuras de vivenda ou traballo. Farán falta profesionais, permisos, supervisión e normativa aplicable.'] },
      { id: 'produccion', title: 'Produción con límites', paragraphs: ['A produción pode ensinar e xerar valor, pero non debe degradar o territorio nin medrar ilimitadamente.'] },
      { id: 'economia', title: 'Economía ao servizo da vida', paragraphs: ['Queremos explorar un modelo mixto. Unha pequena produción non financiaría de inmediato toda a estrutura.'], bullets: ['Administracións e convocatorias.', 'Fundacións, entidades e empresas.', 'Doazóns e cesións.', 'Achegas cando sexa posible.', 'Ingresos de produtos, servizos ou actividades.', 'Proxectos autónomos ou cooperativos.'] },
      { id: 'criterio', title: 'Un criterio para decidir', quote: 'Unha actividade non será valiosa só porque ensine ou xere ingresos. Tamén deberá respectar os límites do territorio e, sempre que sexa posible, contribuír á súa rexeneración.' },
    ] },
    'como-empezar': { title: 'Comezar pequeno. Aprender da realidade.', intro: 'PAIDEIA non necesita comezar como unha gran institución. Necesita reunir un núcleo humano capaz, escoitar un territorio e construír un primeiro piloto que poida probarse con honestidade.', description: 'Folla de ruta fundacional, escala inicial e recursos para un primeiro piloto.', status: 'FASE ACTUAL: CONSTRUCIÓN DO NÚCLEO FUNDADOR', sections: [
      { id: 'fase-1', eyebrow: 'Fase 1 · Actual', title: 'Reunir o núcleo fundador', paragraphs: ['Obxectivo: pasar dunha iniciativa impulsada por unha persoa a un equipo pequeno que comparta responsabilidade.'], bullets: ['Entre 3 e 6 persoas como referencia inicial, non como requisito pechado.', 'Definir principios, límites e goberno.', 'Distribuír responsabilidades e contrastar o modelo.', 'Estudar a forma xurídica e a economía do piloto.', 'Crear unha primeira rede de colaboración.'] },
      { id: 'fase-2', eyebrow: 'Fase 2', title: 'Escoitar e elixir un territorio', bullets: ['Falar con municipios, entidades e veciñanza.', 'Identificar saberes, oficios e posibles mestres.', 'Detectar espazos, terreos e necesidades.', 'Avaliar vivenda, auga, mobilidade, conectividade e servizos.'] },
      { id: 'fase-3', eyebrow: 'Fase 3', title: 'Deseñar o piloto', bullets: ['Definir participantes e entre 2 e 4 proxectos reais.', 'Reunir mestres e profesionais.', 'Resolver convivencia e acompañamento.', 'Preparar orzamento, financiamento, seguros, permisos e prevención.', 'Definir indicadores e protección de menores se fose preciso.'] },
      { id: 'fase-4', eyebrow: 'Fase 4', title: 'Facer, avaliar e corrixir', bullets: ['Executar os proxectos.', 'Avaliar aprendizaxe, autonomía e convivencia.', 'Medir utilidade comunitaria e impacto territorial.', 'Calcular o custo real.', 'Decidir que manter, modificar ou abandonar.'] },
      { id: 'fase-5', eyebrow: 'Fase 5', title: 'Consolidar ou compartir', paragraphs: ['Só despois do piloto se valoraría consolidar o proxecto ou axudar outras comunidades. Non sería unha expansión centralizada nin unha franquía.'] },
      { id: 'piloto', title: 'Primeiro piloto · aproximación inicial', bullets: ['Un municipio pequeno.', 'Entre 8 e 12 participantes.', 'Varios meses.', 'Unha casa ou espazo base.', 'Mestres locais e profesionais externos.', 'Entre 2 e 4 proxectos reais.', 'Avaliación persoal, comunitaria, económica e territorial.'], paragraphs: ['Son unha escala de traballo inicial, non compromisos pechados.'] },
      { id: 'capacidades', title: 'Capacidades necesarias', bullets: ['Visión e coordinación.', 'Operacións e administración.', 'Acompañamento educativo.', 'Facilitación e convivencia.', 'Territorio e rexeneración.', 'Oficios e seguridade.', 'Economía e produción.', 'Comunicación e alianzas.', 'Comunidade e coñecemento local.'], quote: 'Non buscamos títulos nin completar un organigrama. Buscamos persoas fiables, capaces de escoitar, colaborar e asumir responsabilidades reais.' },
      { id: 'recursos', title: 'Que necesita o piloto', bullets: ['Persoas e municipio.', 'Espazo base e vivenda.', 'Terreos, talleres e ferramentas.', 'Alimentación e mobilidade.', 'Financiamento.', 'Seguros e asesoramento legal.', 'Rede de mestres e proxectos reais.', 'Tempo de preparación.'] },
      { id: 'medicion', title: 'Como se mediría', bullets: ['Autonomía e capacidades.', 'Coñecementos transmitidos e continuidade.', 'Necesidades comunitarias atendidas.', 'Espazos recuperados e estado ecolóxico.', 'Actividades económicas iniciadas.', 'Calidade da convivencia.', 'Custo e sustentabilidade.'] },
      { id: 'limites', title: 'Expectativas e límites', quote: 'PAIDEIA non promete resolver por si soa o despoboamento, o desemprego xuvenil nin a perda de oficios. A expectativa inicial é reunir un núcleo capaz, atopar un territorio disposto a colaborar e comprobar cun piloto pequeno se esta forma de aprender, contribuír e convivir xera valor real.' },
    ] },
    origen: { title: 'De onde nace PAIDEIA', intro: 'PAIDEIA nace dunha maneira de entender a aprendizaxe: usar as mans e a cabeza, coidar o próximo e compartir o que descubrimos.', description: 'A orixe de PAIDEIA e o papel inicial de Héctor.', sections: [
      { id: 'origen', title: 'Aprender coas mans e coa cabeza', paragraphs: ['Son Héctor e vivo en L’Argentera, unha vila pequena de Tarragona. Desde pequeno, na casa ensináronme a usar as mans e a cabeza e a non separar unha cousa da outra.', 'Aprendín a moverme entre ámbitos moi diferentes: albanelería, electricidade, fontanería, cociña, xardinería, historia, arte, filosofía ou ciencia. Moitas veces foi tamén unha cuestión de necesidade: non sempre tiñamos moitos cartos, pero si tempo, curiosidade e enxeño para comprender como estaban feitas as cousas e aprender a resolvelas.', 'Iso non significa que sexa experto en todas esas materias. Significa que medrei entendendo o coñecemento como algo vivo: obsérvase, pregúntase, practícase, corríxese e compártese. Nunca deixamos de aprender.'] },
      { id: 'vida-cotidiana', title: 'Unha práctica cotiá', paragraphs: ['Hoxe traballo como informático, pero manteño a miña propia horta, fago reformas na casa e preparo os meus propios embutidos e conservas. En cada tarefa busco aprender, facer as cousas con coidado e ofrecer aos meus a mellor calidade e o máis natural que estea ao meu alcance.', 'Tamén me gusta compartir, contar historias e curiosidades, e pensar que algún día transmitirei todo isto ao meu fillo. Non como unha colección de respostas pechadas, senón como unha maneira de mirar o mundo con atención, autonomía e ganas de seguir descubrindo.'] },
      { id: 'pregunta', title: 'Do persoal a unha pregunta común', paragraphs: ['PAIDEIA nace desa experiencia e do desexo de fomentar o saber, a calma, o enxeño, o coidado e o altruísmo. E dunha pregunta: que ocorrería se volvésemos crear lugares onde aprender facendo, sentirnos útiles, coidar un territorio e transmitir o que sabemos?', 'Deille forma e fixen pública esta primeira proposta, pero non quero construíla só nin presentala como unha idea rematada. Tampouco pretendo ocupar un lugar de experto en ámbitos que precisan coñecementos e experiencias diferentes dos meus.'] },
      { id: 'publico', title: 'Por que facelo público', paragraphs: ['Unha idea de comunidade non pode desenvolverse de maneira privada ou individual. Facela pública incorpora preguntas, desacordos, coñecementos e alianzas.'] },
      { id: 'papel', title: 'O meu papel inicial', paragraphs: ['O meu papel inicial é impulsar a conversa, conectar persoas diferentes, organizar os primeiros pasos e axudar a converter unha intuición nunha proposta que poida contrastarse coa realidade.', 'Non busco seguidores dunha idea rematada. Busco persoas coas que cuestionala, mellorala e compartir progresivamente a responsabilidade. PAIDEIA non debería depender dunha soa persoa.'] },
      { id: 'busco', title: 'Que busco agora', bullets: ['Persoas fundadoras.', 'Experiencia educativa e comunitaria.', 'Coñecemento ambiental e rural.', 'Mestres e profesionais.', 'Municipios interesados.', 'Asesoramento xurídico e económico.', 'Entidades e posibles colaboradores.'] },
      { id: 'no-quiero', title: 'Que non quero que sexa', bullets: ['Un proxecto personalista.', 'Unha promesa grandilocuente.', 'Unha iniciativa imposta desde fóra.', 'Unha idealización da vida rural.', 'Unha marca sen actividade real.', 'Unha organización que medre perdendo o propósito.'] },
    ] },
    participa: { title: 'PAIDEIA comeza reunindo capacidades diferentes', intro: 'Non buscamos unicamente apoio a unha idea. Buscamos persoas, municipios e entidades dispostos a explorar que poderían construír con outros.', description: 'Formas de participar na fase fundacional e contacto.', sections: [
      { id: 'fundar', title: 'Quero axudar a fundar PAIDEIA', paragraphs: ['Para persoas que queiran compartir responsabilidade, decisións e traballo sostido.'] }, { id: 'municipio', title: 'Son un municipio', paragraphs: ['Para concellos ou axentes locais que queiran explorar un posible piloto sen compromisos previos.'] }, { id: 'compartir', title: 'Quero compartir o que sei', paragraphs: ['Para saberes dun oficio, profesión, afección, experiencia ou transmisión familiar. Non fai falta ser docente.'] }, { id: 'participar', title: 'Quero participar', paragraphs: ['Para persoas interesadas nunha experiencia futura. Aínda non hai convocatoria nin calendario pechados.'] }, { id: 'entidad', title: 'Represento unha entidade', paragraphs: ['Para asociacións, fundacións, empresas, administracións ou centros educativos.'] }, { id: 'recursos', title: 'Podo achegar recursos', paragraphs: ['Espazos, terreos, ferramentas, materiais, financiamento, tempo ou conexións poden responder a necesidades reais.'] }, { id: 'contacto', title: 'Abramos a conversa', paragraphs: ['Cóntanos desde onde escribes e que che gustaría explorar. Contactar non implica compromiso.'] },
    ] },
  },
}
export default gl
