import type { LanguageCode } from './index.ts'

export type EditorialImageKey = 'hero' | 'learning' | 'community' | 'territory' | 'masters' | 'economy' | 'pilot' | 'participate'

export const imageAlt: Record<LanguageCode, Record<EditorialImageKey, string>> = {
  ca: { hero: 'Persones de diferents generacions reparen una peça de fusta en un taller rural.', learning: 'Dues persones construeixen juntes un mur de pedra seca.', community: 'Veïnes i veïns comparteixen taula en una plaça de poble.', territory: 'Poble entre camps, horts i bosc després de la pluja.', masters: 'Una artesana ensenya cistelleria a una jove.', economy: 'Un petit taller cooperatiu prepara conserves i objectes de fusta.', pilot: 'Un grup planifica un projecte de poble al voltant d’un mapa.', participate: 'Tres persones arriben a un espai de treball compartit amb eines i planters.' },
  es: { hero: 'Personas de distintas generaciones reparan una pieza de madera en un taller rural.', learning: 'Dos personas construyen juntas un muro de piedra seca.', community: 'Vecinas y vecinos comparten mesa en una plaza de pueblo.', territory: 'Pueblo entre campos, huertos y bosque después de la lluvia.', masters: 'Una artesana enseña cestería a una joven.', economy: 'Un pequeño taller cooperativo prepara conservas y objetos de madera.', pilot: 'Un grupo planifica un proyecto de pueblo alrededor de un mapa.', participate: 'Tres personas llegan a un espacio de trabajo compartido con herramientas y semilleros.' },
  eu: { hero: 'Belaunaldi desberdinetako pertsonek egurrezko pieza bat konpontzen dute landa-tailer batean.', learning: 'Bi pertsonak harrizko horma lehor bat eraikitzen dute elkarrekin.', community: 'Herriko bizilagunek mahaia partekatzen dute plazan.', territory: 'Herria soro, baratze eta basoen artean, euriaren ondoren.', masters: 'Artisau batek saskigintza irakasten dio gazte bati.', economy: 'Kooperatiba-tailer txiki batek kontserbak eta egurrezko objektuak prestatzen ditu.', pilot: 'Talde batek herri-proiektu bat planifikatzen du mapa baten inguruan.', participate: 'Hiru pertsona tresna eta landareekin iristen dira lanerako espazio partekatu batera.' },
  gl: { hero: 'Persoas de distintas xeracións reparan unha peza de madeira nun obradoiro rural.', learning: 'Dúas persoas constrúen xuntas un muro de pedra seca.', community: 'A veciñanza comparte mesa nunha praza da aldea.', territory: 'Aldea entre campos, hortas e bosque despois da chuvia.', masters: 'Unha artesá ensina cestería a unha moza.', economy: 'Un pequeno obradoiro cooperativo prepara conservas e obxectos de madeira.', pilot: 'Un grupo planifica un proxecto de aldea arredor dun mapa.', participate: 'Tres persoas chegan a un espazo de traballo compartido con ferramentas e viveiros.' },
}
